// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package network.p2p;

public final class MessageOuterClass {
  private MessageOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_network_p2p_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_network_p2p_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\022\013network.p2p\032\033google/pro" +
      "tobuf/empty.proto\"M\n\007Message\022\020\n\010OriginId" +
      "\030\001 \001(\014\022\021\n\tTargetIds\030\002 \003(\014\022\017\n\007Payload\030\003 \001" +
      "(\014\022\014\n\004Type\030\004 \001(\t2H\n\tMessenger\022;\n\007Deliver" +
      "\022\024.network.p2p.Message\032\026.google.protobuf" +
      ".Empty\"\000(\001B\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_network_p2p_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_network_p2p_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_network_p2p_Message_descriptor,
        new java.lang.String[] { "OriginId", "TargetIds", "Payload", "Type", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
