// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: storage.proto

package network.p2p.proto;

public interface GetReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:network.p2p.proto.GetReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes Payload = 1;</code>
   * @return The payload.
   */
  com.google.protobuf.ByteString getPayload();

  /**
   * <code>string Type = 2;</code>
   * @return The type.
   */
  String getType();
  /**
   * <code>string Type = 2;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();
}
