// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: storage.proto

package network.p2p.proto;

public interface GetRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:network.p2p.proto.GetRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes Identifier = 1;</code>
   * @return The identifier.
   */
  com.google.protobuf.ByteString getIdentifier();

  /**
   * <code>string Channel = 2;</code>
   * @return The channel.
   */
  String getChannel();
  /**
   * <code>string Channel = 2;</code>
   * @return The bytes for channel.
   */
  com.google.protobuf.ByteString
      getChannelBytes();
}
