// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: storage.proto

package network.p2p.proto;

public final class StorageOuterClass {
  private StorageOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_network_p2p_proto_PutMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_network_p2p_proto_PutMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_network_p2p_proto_GetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_network_p2p_proto_GetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_network_p2p_proto_GetReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_network_p2p_proto_GetReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rstorage.proto\022\021network.p2p.proto\032\033goog" +
      "le/protobuf/empty.proto\"N\n\nPutMessage\022\020\n" +
      "\010OriginId\030\001 \001(\014\022\017\n\007Channel\030\002 \001(\t\022\017\n\007Payl" +
      "oad\030\003 \001(\014\022\014\n\004Type\030\004 \001(\t\"1\n\nGetRequest\022\022\n" +
      "\nIdentifier\030\001 \001(\014\022\017\n\007Channel\030\002 \001(\t\")\n\010Ge" +
      "tReply\022\017\n\007Payload\030\001 \001(\014\022\014\n\004Type\030\002 \001(\t2\224\001" +
      "\n\007Storage\022@\n\003Put\022\035.network.p2p.proto.Put" +
      "Message\032\026.google.protobuf.Empty\"\000(\001\022G\n\003G" +
      "et\022\035.network.p2p.proto.GetRequest\032\033.netw" +
      "ork.p2p.proto.GetReply\"\000(\0010\001B\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_network_p2p_proto_PutMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_network_p2p_proto_PutMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_network_p2p_proto_PutMessage_descriptor,
        new String[] { "OriginId", "Channel", "Payload", "Type", });
    internal_static_network_p2p_proto_GetRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_network_p2p_proto_GetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_network_p2p_proto_GetRequest_descriptor,
        new String[] { "Identifier", "Channel", });
    internal_static_network_p2p_proto_GetReply_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_network_p2p_proto_GetReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_network_p2p_proto_GetReply_descriptor,
        new String[] { "Payload", "Type", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
