package modules.logger;

import model.lightchain.Identifier;
import org.slf4j.LoggerFactory;

/**
 * Encapsulates logger for lightchain project.
 */
public class LightchainLogger {
  /**
   * Logger prefix that is used to filter out logs generated by this project.
   */
  private static final String LOGGER_NAME = "io.github.yhassanzadeh13";

  /**
   * Creates a logger for the given class name prefixed by the logger name.
   *
   * @param className class name for which a logger is created.
   * @return logger for the class.
   */
  public static Logger getLogger(String className) {
    return new Logger(LoggerFactory.getLogger(LOGGER_NAME + "." + className));
  }

  /**
   * Creates a logger prefixed with the node id for the given class name prefixed by the logger name.
   *
   * @param className class name for which a logger is created.
   * @param nodeId    node id for which a logger is created.
   * @return logger for the class and node id.
   */
  public static Logger getLogger(String className, Identifier nodeId) {
    Logger logger = new Logger(LoggerFactory.getLogger(LOGGER_NAME + "." + className));
    logger.addPrefix("node_id: " + nodeId.toString());
    return logger;
  }
}
