package modules.logger;

import org.slf4j.LoggerFactory;

/**
 * Encapsulates logger for lightchain project.
 */
public class LightchainLogger {
  /**
   * Logger prefix that is used to filter out logs generated by this project.
   */
  private static final String LOGGER_NAME = "io.github.yhassanzadeh13";

  /**
   * Creates a logger for the given class name prefixed by the logger name.
   *
   * @param className class name for which a logger is created.
   * @return logger for the class.
   */
  public static org.slf4j.Logger getLogger(String className) {
    return LoggerFactory.getLogger(LOGGER_NAME + "." + className);
  }
}
